cdip_admin/accounts/admin.py, cdip_admin/api/v2/tests/test_eula_api.py, cdip_admin/api/v2/views.py
- Makes the `/eula/` endpoint return 404 when there isn't an active EULA
- Disallow changing the active field while adding new EULAs from the Django admin
- Adds test coverage for the negative scenario where there isn't an active EULA
Screenshoot of the Django admin while adding a new EULA  (active is read only)
[GUNDI-3065](https://allenai.atlassian.net/browse/GUNDI-3065)
[GUNDI-3065]: https://allenai.atlassian.net/browse/GUNDI-3065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3065: EULA API Improvements

.pre-commit-config.yaml, .secrets.baseline, cdip_admin/api/v2/tests/test_activity_logs_api.py, cdip_admin/api/v2/tests/test_connections_api.py, cdip_admin/api/v2/tests/test_integrations_api.py, cdip_admin/api/v2/tests/test_routes_api.py, cdip_admin/api/v2/tests/test_sources_api.py, cdip_admin/conftest.py, cdip_admin/deployments/management/commands/dispatchers.py, cdip_admin/deployments/tests/test_commands.py, cdip_admin/integrations/models/v1/models.py, cdip_admin/integrations/models/v2/models.py
- Extends our `dispatchers` command to support updating the source, so that we can deploy new versions.
- The command supports dispatchers v1 and v2 for ER, SMART and WPS Watch.
- It also supports updating dispatchers in bulk by type, or updating a single one by id.
- Adds test coverage for the different usages of the command combined with different types and versions
```
$ python3 manage.py dispatchers --v1 --type earth_ranger --max 2 --update-source er-dispatcher-src-release-202405091336-4a30801.zip
$ python3 manage.py dispatchers --v2 --type smart_connect --max 2 --update-source "gcr.io/cdip-78ca/gundi/smart-dispatcher:release-202405092019-2c1155b"
$ python3 manage.py dispatchers --v1 --integration c7ea23bf-ac1c-4f49-be44-5ae1eb2b0898 --update-source …
```
=> GUNDI-3096: Update dispatchers command

cdip_admin/cdip_admin/settings.py, cdip_admin/cdip_admin/urls.py, dependencies/requirements.in, dependencies/requirements.txt
Adds django-silk for debugging slow requests and/or queries. 
This can be enabled by setting env var `DJANGO_SILK_ENABLED = True` (disabled by default)
Example of what we can get:
=> Add django-silk for debugging

docker/Dockerfile
Small update it the Dockerfile so when we run collectstatic during the build, the static files for django silk are included.
=> Update dockerfile to collect django-silk static files

cdip_admin/integrations/models/v1/models.py, cdip_admin/integrations/models/v2/models.py
- Change scheme from `http` to `https`
- Add port to base_url if present
If the site is ER, the `base_url` will only contain scheme,  hostname and port (to avoid any path present)
=> Sanitize URL if the integration is ER type

cdip_admin/api/v2/serializers.py, cdip_admin/api/v2/tests/test_actions_execution_api.py, cdip_admin/api/v2/tests/utils.py, cdip_admin/integrations/models/v2/models.py
- Adds support for triggering integration actions with a new config provided in the request instead of using the config stored in the DB. This is for cases such as testing new credentials in a configuration before saving them.
- Adds test coverage
[GUNDI-3234](https://allenai.atlassian.net/browse/GUNDI-3234)
[GUNDI-3234]: https://allenai.atlassian.net/browse/GUNDI-3234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3234: Support actions execution with config overrides

.secrets.baseline, cdip_admin/conftest.py, cdip_admin/event_consumers/dispatcher_events_consumer.py, cdip_admin/event_consumers/tests/test_dispatcher_events_consumer.py
- Fixes an issue processing events coming from the smart dispatcher when related_to is blank
- Adds test coverage for the bugfix
[GUNDI-2963](https://allenai.atlassian.net/browse/GUNDI-2963)
[GUNDI-2963]: https://allenai.atlassian.net/browse/GUNDI-2963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-2963: Fix issue processing dispatcher events

cdip_admin/api/v2/tests/test_attachments_api.py, cdip_admin/api/v2/utils.py, cdip_admin/conftest.py
- Fixes an issue in queries related to attachments, for the case when a related event was delivered to more than one destination
- Add guardrails in other similar queries
- Adds test coverage for the bugfixes
[GUNDI-3339](https://allenai.atlassian.net/browse/GUNDI-3339)
[GUNDI-3339]: https://allenai.atlassian.net/browse/GUNDI-3339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3339:  Improve traces queries with multple destinations

dependencies/requirements-dev.txt, dependencies/requirements.in, dependencies/requirements.txt
This is an update to the cdip-connector dependency. The latest having the feature to allow disabling tracing as well as the latest edits for job-partitioning (job-partitioning is only relevant for Gundi V1 functions).
[GUNDI-3125](https://allenai.atlassian.net/browse/GUNDI-3125)
[GUNDI-3125]: https://allenai.atlassian.net/browse/GUNDI-3125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update cdip-connector version.

.github/workflows/values/dev.yml, .github/workflows/values/prod.yml, .github/workflows/values/stage.yml
Add an extra environment variable called `BUCKET_NAME` and have it be the same as `GS_BUCKET_NAME`.
This will allow code using GoogleCloudStorage within the legacy cdip-connector library to find the appropriate storage bucket for storing attachments.
=> Add extra "BUCKET_NAME" variable for legacy cdip-connector

.secrets.baseline, cdip_admin/api/serializers.py, cdip_admin/api/v2/serializers.py, cdip_admin/api/v2/tests/test_events_api.py, cdip_admin/api/v2/utils.py, cdip_admin/conftest.py, dependencies/requirements-dev.txt, dependencies/requirements.in, dependencies/requirements.txt
- Adds a `status` field in API v2 for events and event updates
- Updates gundi-core and gundi-client versions
[GUNDI-3334](https://allenai.atlassian.net/browse/GUNDI-3334)
[GUNDI-3334]: https://allenai.atlassian.net/browse/GUNDI-3334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3334: Add status field in API v2

.secrets.baseline, cdip_admin/conftest.py, cdip_admin/event_consumers/dispatcher_events_consumer.py, cdip_admin/event_consumers/tests/test_dispatcher_events_consumer.py
- Extends the dispatcher events consumer to show a message in activity logs when the WPS Watch dispatcher buffers an event in wait for an attachment.
- Extends the test coverage accordingly
[GUNDI-3249](https://allenai.atlassian.net/browse/GUNDI-3249)
[GUNDI-3249]: https://allenai.atlassian.net/browse/GUNDI-3249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3249: Consume wpswatch dispatcher custom logs

.secrets.baseline, cdip_admin/api/v2/tests/test_connections_api.py, cdip_admin/conftest.py, cdip_admin/integrations/filters.py
- Extends filters in the `/connections/` endpoint to support filtering by `destination_id`
- Extends the test coverage accordingly
[GUNDI-2571](https://allenai.atlassian.net/browse/GUNDI-2571)
[GUNDI-2571]: https://allenai.atlassian.net/browse/GUNDI-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-2571: Filter connections by destiantion id

cdip_admin/deployments/admin.py, cdip_admin/deployments/management/commands/dispatchers.py, cdip_admin/deployments/models.py, cdip_admin/deployments/tasks.py, cdip_admin/deployments/tests/test_commands.py, cdip_admin/deployments/utils.py
- Updates the deployment code to avoid using eventarc triggers for ER, SMART and WPS Watch
- Adds commands to re-create dispatchers for ER, SMART and WPS Watch
- Adds support for re-creating dispatchers from the admin
- Adds support for searching and filtering dispatchers in the admin
- Extends test coverage for dispatcher commands
- Fixes an issue deleting dispatchers
[GUNDI-3376](https://allenai.atlassian.net/browse/GUNDI-3376)
[GUNDI-3376]: https://allenai.atlassian.net/browse/GUNDI-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3376: Dispatchers re-create command

cdip_admin/activity_log/management/commands/partition_activity_logs.py
Hotfix applied in prod to skip running vacuum analyze in the partitioning command as it may take very long and can be run separately later.
=> Skip running vacuum analize after partitioning

.secrets.baseline, cdip_admin/conftest.py, cdip_admin/event_consumers/dispatcher_events_consumer.py, cdip_admin/event_consumers/tests/test_dispatcher_events_consumer.py
- Modify activity log titles to differentiate delivery events by stream type (events, observations, attachments)
[GUNDI-3558](https://allenai.atlassian.net/browse/GUNDI-3558)
[GUNDI-3558]: https://allenai.atlassian.net/browse/GUNDI-3558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3558: Show stream type in activity logs title

cdip_admin/activity_log/mixins.py, cdip_admin/api/v2/tests/utils.py, cdip_admin/integrations/models/v2/models.py
- Adds support for specifying a field to display as ID in activity logs of creation type.
- Shows the external ID in activity logs on source creation
`Source CREATED (Z9Y8X7W6V5U4)`
[GUNDI-3560](https://allenai.atlassian.net/browse/GUNDI-3560)
[GUNDI-3560]: https://allenai.atlassian.net/browse/GUNDI-3560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3560: Show source id in activity logs

cdip_admin/integrations/models/v2/models.py, cdip_admin/integrations/tests/test_actions_scheduling.py
- Adds support for disabling pull integrations. The related periodic task is enabled/disabling according to the integration enabled status.
[GUNDI-3242](https://allenai.atlassian.net/browse/GUNDI-3242)
[GUNDI-3242]: https://allenai.atlassian.net/browse/GUNDI-3242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3242: Support disabling pull integrations

cdip_admin/integrations/models/v2/models.py, cdip_admin/integrations/tests/test_calc_integration_status.py
- Updates the health status immediately after enabling/disabling integrations and when they are created as disabled.
[GUNDI-3801](https://allenai.atlassian.net/browse/GUNDI-3801)
[GUNDI-3801]: https://allenai.atlassian.net/browse/GUNDI-3801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3801: Update health status on integration enable/disable

.secrets.baseline, cdip_admin/api/v2/tests/test_connections_api.py, cdip_admin/conftest.py, cdip_admin/integrations/filters.py
- Fixes an issue where `disabled` connections were wrongly returned when filtering by `unhealthy` (due to `unhealthy` destinations)
[GUNDI-3781](https://allenai.atlassian.net/browse/GUNDI-3781)
[Connection Status Calc](https://allenai.atlassian.net/wiki/spaces/CDIP/pages/30428528641/Health+Indicators+WIP#Connection-status-aggregation-matrix)
[GUNDI-3781]: https://allenai.atlassian.net/browse/GUNDI-3781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3781: Fix connection status filter

.github/workflows/main.yml, .secrets.baseline, cdip_admin/conftest.py, cdip_admin/event_consumers/dispatcher_events_consumer.py, cdip_admin/event_consumers/tests/test_dispatcher_events_consumer.py, dependencies/requirements-dev.txt, dependencies/requirements.in, dependencies/requirements.txt
- Updates gundi-core and modified the dispatcher events consumer to process the latest events published by dispatchers which contain more info on errors including the traceback, server response status, and the response body. This extra info is now stored in activity logs under "details" so that we can see it in the portal and use it for troubleshooting
- Contemplates that dispatchers running an older version of the code may be publishing events with an older schema. Both schema versions are supported. v1 schema events, which don't carry extra error details, are converted to v2 schema events setting a default error message like "Delivery Failed at the Dispatcher. Please update this dispatcher to see more details here."  …
=> GUNDI-3559: Improve activity logs on dispatcher errors

.github/workflows/main.yml, .secrets.baseline, cdip_admin/conftest.py, cdip_admin/event_consumers/integration_events_consumer.py, cdip_admin/event_consumers/tests/test_integration_events_consumer.py, dependencies/requirements-dev.txt, dependencies/requirements.in, dependencies/requirements.txt
- Updates gundi-core and modified the integration events consumer to process the latest events published by connectors which contain more info on errors including the traceback, server response status, and the response body, when available. This extra info is now stored in activity logs under "details" so that we can see it in the portal and use it for troubleshooting
[GUNDI-3912](https://allenai.atlassian.net/browse/GUNDI-3912)
[GUNDI-3912]: https://allenai.atlassian.net/browse/GUNDI-3912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3912: Save extra details on connector errors

.secrets.baseline, cdip_admin/cdip_admin/settings.py, cdip_admin/conftest.py, cdip_admin/emails/templates/unhealthy_connections_email.html, cdip_admin/integrations/tasks.py, cdip_admin/integrations/tests/test_email_alerts.py
- Exclude disabled connections from the "unhealthy connections" email. If there are only disabled connections, the email isn't sent at all. There's also a setting to enable/disable this behavior.
[GUNDI-3997](https://allenai.atlassian.net/browse/GUNDI-3997)
[GUNDI-3997]: https://allenai.atlassian.net/browse/GUNDI-3997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-3881: Exclude disabled in the unhealthy connections email

.secrets.baseline, cdip_admin/api/v2/tests/test_integrations_api.py, cdip_admin/conftest.py, cdip_admin/integrations/filters.py
This PR adds a query param filter `is_used_as_provider=<true|false>` that will allow us to filter out integrations being used as data providers so that they don't show up in the destinations list in the portal. Test coverage is extended accordingly.
=> GUNDI-4129: Add filter 'is_used_as_provider' in integrations api

.secrets.baseline, cdip_admin/accounts/management/commands/api_consumers.py, cdip_admin/accounts/tests/test_commands.py, cdip_admin/conftest.py, cdip_admin/integrations/tests/test_utils.py, cdip_admin/integrations/utils.py
- Updates the consumer creation logic to save the `integration_type` in `consumer_info.custom_id`
- Adds a command to manage consumer info, to allow adding `integration_type` in pre-existent consumers
[GUNDI-4152](https://allenai.atlassian.net/browse/GUNDI-4152)
[GUNDI-4152]: https://allenai.atlassian.net/browse/GUNDI-4152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GUNDI-4152: Update consumer info for alerting

.secrets.baseline, cdip_admin/api/v2/serializers.py, cdip_admin/api/v2/tests/test_activity_logs_api.py, cdip_admin/api/v2/views.py
This pull request refactors the `ActivityLogs` feature to improve performance and modularity. It introduces a base serializer for activity logs, optimizes database queries by deferring unnecessary fields during list operations, and adds a new test for retrieving activity log details. Additionally, minor updates were made to `.secrets.baseline`.
* Renamed `ActivityLogRetrieveSerializer` to `ActivityLogBaseSerializer` and introduced a new `ActivityLogDetailsSerializer` to handle detailed log retrieval. (`cdip_admin/api/v2/serializers.py` - [[1]](diffhunk://#diff-46b71600be12187985851c9e97b3631f862fa709770df13e08d5238d63f3f087L1162-R1162) [[2]](diffhunk://#diff-46b71600be12187985851c9e97b3631f862fa709770df13e08d5238d63f3f087L1172-R1179)
* Updated `ActivityLogsViewSet` to use …
=> GUNDI-4240: Return activity log details in separate endpoint

.secrets.baseline, cdip_admin/conftest.py, cdip_admin/event_consumers/dispatcher_events_consumer.py, cdip_admin/event_consumers/tests/test_dispatcher_events_consumer.py
This PR changes the log level of delivery errors on ER 409s (conflict) to warning, so that connections bringing more than one observation pero second per source are not flagged as unhealthy (e.g. Hytera radios)
=> Log ER 409s as warings in activity logs

.secrets.baseline, cdip_admin/api/v2/tests/test_gunditrace_serializer.py, cdip_admin/conftest.py, cdip_admin/integrations/management/commands/set_action_configs.py, cdip_admin/integrations/tests/test_commands.py, cdip_admin/integrations/tests/test_tasks.py
This pull request introduces a new management command for creating or updating action configurations for integrations, along with supporting fixtures and tests. It also includes minor updates to test files and the secrets baseline. The most significant changes are the addition of the `set_action_configs` management command and its comprehensive test coverage.
**New management command and tests:**
* Added a new Django management command `set_action_configs` in `cdip_admin/integrations/management/commands/set_action_configs.py` to create or update `IntegrationConfiguration` objects for a given integration or integration type, action, and configuration data. The command supports filtering by integration, integration type, action, and limits the number of processed integrations.
* Added tests …
=> GUNDI-4666: Add command to add missing action configs

.secrets.baseline, cdip_admin/api/v2/tests/test_integrations_api.py, cdip_admin/integrations/models/v2/models.py, cdip_admin/integrations/models/v2/services.py
This PR fixes the issue that caused false errors in activity logs and alerts due to pull actions being triggered for ER destinations.
Copilot:
This pull request introduces improvements to how periodic tasks are enabled or disabled for integrations, based on whether the integration is used as a provider. It adds new properties to the `Integration` model to clarify its usage context and refines the logic for managing periodic tasks, ensuring they are only active when appropriate. The changes also update related test cases and service logic for consistency.
**Integration model enhancements:**
* Added `is_used_as_provider` and `is_used_as_destination` properties to the `Integration` model to clearly indicate its role in routing rules.
* Introduced the `periodic_pull_action_configurations` …
=> GUNDI-4676: Fix pull action tasks being triggered for ER destiantions

dependencies/requirements-dev.txt, dependencies/requirements.in, dependencies/requirements.txt
This PR upgrades the gunicorn version to fix a Python version compatibility issue detected while testing in dev
=> Update gunicorn version for python 3.11
